#!/bin/sh

# Extract all poses from supplied video and save images and json

OUTPUT="$(basename "$1" .mp4)_out"
mkdir "$OUTPUT"
./build/examples/openpose/openpose.bin --video "$1" --write_images "$OUTPUT" --write_json "$OUTPUT"
